### ISSUE TITLE
Error installing Plugin

### ISSUE THREAD

**Issue by beltoftandersen** [RebelCode/eddbk#11]
Getting this error when activating the plugin:

Plugin could not be activated because it triggered a fatal error.

**Comment by danmaby** [comment]
Receiving a fatal error on plugin activation too:

```Fatal error: Uncaught Error: Class 'RebelCode\EddBookings\Core\ExceptionHandler' not found in /app/public/wp-content/plugins/eddbk/plugin.php:271 Stack trace: #0 /app/public/wp-content/plugins/eddbk/plugin.php(181): getEddBkErrorHandler() #1 /app/public/wp-content/plugins/eddbk/plugin.php(89): runEddBkCore() #2 /app/public/wp-admin/includes/plugin.php(2255): include('/app/public/wp-...') #3 /app/public/wp-admin/plugins.php(177): plugin_sandbox_scrape('eddbk/plugin.ph...') #4 {main} thrown in /app/public/wp-content/plugins/eddbk/plugin.php on line 271```
